FROM alpine:3.5

COPY tmp/frpc /frpc
COPY tmp/frps /frps
COPY conf/frpc_min.ini /frpc.ini
COPY conf/frps_min.ini /frps.ini

WORKDIR /

EXPOSE 22 10080 10443 3389 17000 17500 18000-19999

ENTRYPOINT ["/frps"]
